### ISSUE TITLE
Fix why publishing does not appear in update-center

### ISSUE THREAD

**Issue by vvitayau** [groupon/DotCi-Plugins-Starter-Pack#12]
DotCi-Plugins-Starter-Pack publish to http://repo.jenkins-ci.org/releases/com/groupon/jenkins/plugins/DotCi-Plugins-Starter-Pack/ but does not appear in https://updates.jenkins-ci.org/download/plugins/

Interesting that DotCi-Plugins-Starter-Pack:1.6.2 has no problems via https://github.com/jenkinsci/docker/blob/master/plugins.sh but I DID HAVE [an issue with DotCi-Plugins-Starter-Pack:1.7.1](https://github.com/DotCi/jenkinsci-dotci-example/commit/48d754659825516fd3370be50943e48649967b43) ???

Therefore I like to properly fix this problem to resolve above inconsistency.
Similar issue happened and now fixed for DotCi-InstallPackages plugin.

**Comment by vvitayau** [comment]
Got to wait 4 hours to confirm per https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Help\!Mypluginisnotshowingupintheupdatecenter

**Comment by vvitayau** [comment]
Created https://wiki.jenkins-ci.org/display/JENKINS/DotCi+Plugins+Starter+Pack+Plugin and hopefully it will look as nice as https://wiki.jenkins-ci.org/display/JENKINS/DotCi+Plugin

**Comment by vvitayau** [comment]
:clap: 

https://updates.jenkins-ci.org/download/plugins/DotCi-Plugins-Starter-Pack/ now available
https://wiki.jenkins-ci.org/display/JENKINS/DotCi+Plugins+Starter+Pack+Plugin looks wonderful

To-do: request forked repo to avoid 404 for https://github.com/jenkinsci/DotCi-Plugins-Starter-Pack-plugin

**Comment by orrc** [comment]
> To-do: request forked repo to avoid 404 for https://github.com/jenkinsci/DotCi-Plugins-Starter-Pack-plugin

If you're using this repo as the standard, please don't fork unnecessarily into `jenkinsci`, as that will just confuse people.

I've updated your wiki page to point to this repo:
https://wiki.jenkins-ci.org/pages/diffpages.action?pageId=87625363&originalId=88572053
