### ISSUE TITLE
Plugins not supported?

### ISSUE THREAD

**Issue by Dinoshauer** [groupon/DotCi-Plugins-Starter-Pack#3]
Hello!

I'm trying to get my python test reports published to jenkins but when I try to use the `test_output` plugin (this happens with `ansicolor` as well, but I don't know if that's how you're supposed to define it?) I get the following error in my console:

    ERROR: Plugin test_output not supported

Here's my .ci.yml

    image: python3
    command:
      - pip install -r requirements.txt
      - py.test test.py --junitxml=test-report.xml
    notifications:
      - hipchat: my-room
    plugins: 
      - test_output: 
          format: tap |junit

However notifications works fine, also. Is it possible to define another output than TAP in the settings? (I can't really find any documentation on the plugins anywhere :cry: )

EDIT: Though it'd be nice to have some system info on this ticket as well

Jenkins ver. 1.580
DotCI: 2.5.4
DotCi-Plugins-Starter-Pack: 1.1.1
Ubuntu 14.04

**Comment by Dinoshauer** [comment]
Update: So I got this to work by setting:

    plugins:
      - junit

Jenkins now outputs:

    Recording test results

But I can't see any test results anywhere in the UI though

**Comment by suryagaddipati** [comment]
Thanks for the bug report. They should be visible on build level. 

Closing this issue for now. Feel free to reopen it that is not the case.
